-- 코드를 작성해주세요
# SELECT A.ID, COUNT(B.PARENT_ID) AS CHILD_COUNT FROM ECOLI_DATA A
# LEFT JOIN ECOLI_DATA B ON B.PARENT_ID = A.ID
# GROUP BY A.ID 
# ORDER BY A.ID;

SELECT A.ID, (SELECT COUNT(*) FROM ECOLI_DATA B
           WHERE B.PARENT_ID = A.ID) AS CHILD_COUNT
FROM ECOLI_DATA A
ORDER BY A.ID;
